/*
 * Nsoraf_SOR
 *
 * Nsoraf Steering Of Roaming Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (

)


type TraceData struct {
 


	// TraceRef string
		// base name traceRef
	// complexType=
	// datatypeWithEnum string
	// dataFormat
	// baseTypestring
	// containerType
	//  isPrimitiveType



	TraceRef string `json:"traceRef" yaml:"traceRef" bson:"traceRef" mapstructure:"TraceRef"`
 


	// TraceDepth TraceDepth
		// base name traceDepth
	// complexType=TraceDepth
	// datatypeWithEnum TraceDepth
	// dataFormat
	// baseTypeTraceDepth
	// containerType
	//  



	TraceDepth TraceDepth `json:"traceDepth" yaml:"traceDepth" bson:"traceDepth" mapstructure:"TraceDepth"`
 


	// NeTypeList string
		// base name neTypeList
	// complexType=
	// datatypeWithEnum string
	// dataFormat
	// baseTypestring
	// containerType
	//  isPrimitiveType



	NeTypeList string `json:"neTypeList" yaml:"neTypeList" bson:"neTypeList" mapstructure:"NeTypeList"`
 


	// EventList string
		// base name eventList
	// complexType=
	// datatypeWithEnum string
	// dataFormat
	// baseTypestring
	// containerType
	//  isPrimitiveType



	EventList string `json:"eventList" yaml:"eventList" bson:"eventList" mapstructure:"EventList"`
 


	// CollectionEntityIpv4Addr string
		// base name collectionEntityIpv4Addr
	// complexType=
	// datatypeWithEnum string
	// dataFormat
	// baseTypestring
	// containerType
	//  isPrimitiveType



	CollectionEntityIpv4Addr *string `json:"collectionEntityIpv4Addr,omitempty" yaml:"collectionEntityIpv4Addr" bson:"collectionEntityIpv4Addr" mapstructure:"CollectionEntityIpv4Addr"`
 


	// CollectionEntityIpv6Addr Ipv6Addr
		// base name collectionEntityIpv6Addr
	// complexType=Ipv6Addr
	// datatypeWithEnum Ipv6Addr
	// dataFormat
	// baseTypeIpv6Addr
	// containerType
	//  



	CollectionEntityIpv6Addr *Ipv6Addr `json:"collectionEntityIpv6Addr,omitempty" yaml:"collectionEntityIpv6Addr" bson:"collectionEntityIpv6Addr" mapstructure:"CollectionEntityIpv6Addr"`
 


	// InterfaceList string
		// base name interfaceList
	// complexType=
	// datatypeWithEnum string
	// dataFormat
	// baseTypestring
	// containerType
	//  isPrimitiveType



	InterfaceList *string `json:"interfaceList,omitempty" yaml:"interfaceList" bson:"interfaceList" mapstructure:"InterfaceList"`
}
