/*
 * Nsoraf_SOR
 *
 * Nsoraf Steering Of Roaming Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import ()

type NfType string

// enum type
// List of NfType
const (
	NFTYPE_NRF      NfType = "NRF"
	NFTYPE_UDM      NfType = "UDM"
	NFTYPE_AMF      NfType = "AMF"
	NFTYPE_SMF      NfType = "SMF"
	NFTYPE_AUSF     NfType = "AUSF"
	NFTYPE_NEF      NfType = "NEF"
	NFTYPE_PCF      NfType = "PCF"
	NFTYPE_SMSF     NfType = "SMSF"
	NFTYPE_NSSF     NfType = "NSSF"
	NFTYPE_SORAF    NfType = "SORAF"
	NFTYPE_LMF      NfType = "LMF"
	NFTYPE_GMLC     NfType = "GMLC"
	NFTYPE__5_G_EIR NfType = "5G_EIR"
	NFTYPE_SEPP     NfType = "SEPP"
	NFTYPE_UPF      NfType = "UPF"
	NFTYPE_N3_IWF   NfType = "N3IWF"
	NFTYPE_AF       NfType = "AF"
	NFTYPE_UDSF     NfType = "UDSF"
	NFTYPE_BSF      NfType = "BSF"
	NFTYPE_CHF      NfType = "CHF"
	NFTYPE_NWDAF    NfType = "NWDAF"
	NFTYPE_PCSCF    NfType = "PCSCF"
	NFTYPE_CBCF     NfType = "CBCF"
	NFTYPE_HSS      NfType = "HSS"
	NFTYPE_UCMF     NfType = "UCMF"
	NFTYPE_SOR_AF   NfType = "SOR_AF"
	NFTYPE_SPAF     NfType = "SPAF"
	NFTYPE_MME      NfType = "MME"
	NFTYPE_SCSAS    NfType = "SCSAS"
	NFTYPE_SCEF     NfType = "SCEF"
	NFTYPE_SCP      NfType = "SCP"
	NFTYPE_NSSAAF   NfType = "NSSAAF"
	NFTYPE_ICSCF    NfType = "ICSCF"
	NFTYPE_SCSCF    NfType = "SCSCF"
	NFTYPE_DRA      NfType = "DRA"
	NFTYPE_IMS_AS   NfType = "IMS_AS"
	NFTYPE_CEF      NfType = "CEF"
)
