/*
 * Nsoraf_SOR
 *
 * Nsoraf Steering Of Roaming Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import ()

type Snssai struct {
	// simple type

	Sst int32 `json:"sst" yaml:"sst" bson:"sst" mapstructure:"Sst"`

	Sd *string `json:"sd,omitempty" yaml:"sd" bson:"sd" mapstructure:"Sd"`
}
