/*
 * Nsoraf_SOR
 *
 * Nsoraf Steering Of Roaming Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import ()

type SorAckStatus string

// enum type
// List of SorAckStatus
const (
	SORACKSTATUS_SUCCESSFUL     SorAckStatus = "ACK_SUCCESSFUL"
	SORACKSTATUS_NOT_RECEIVED   SorAckStatus = "ACK_NOT_RECEIVED"
	SORACKSTATUS_NOT_SUCCESSFUL SorAckStatus = "ACK_NOT_SUCCESSFUL"
)
