/*
 * Nsoraf_SOR
 *
 * Nsoraf Steering Of Roaming Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import ()

type InvalidParam1 struct {
	// simple type

	// Attribute's name encoded as a JSON Pointer, or header's name.

	Param string `json:"param" yaml:"param" bson:"param" mapstructure:"Param"`

	// A human-readable reason, e.g. \"must be a positive integer\".

	Reason *string `json:"reason,omitempty" yaml:"reason" bson:"reason" mapstructure:"Reason"`
}
